### ISSUE TITLE
Output in GUI

### ISSUE THREAD

**Issue by Aluriak** [Nedgang/clitogui#3]
In some cases, the output of the decorated python script is itself a displayable object (an image, typically).

Could we think about a way to get clitogui to not only decorate the CLI, but also to retrieve and print the final results ?

My use case is a generator of image generator : the program is generating a CLI, which generates an image depending of the CLI options. Currently, decorating the generated CLI with clitogui will only provide a GUI for the CLI, but the final output will have to be opened with another program.

What about something like:

    def my_running_method(gui_options):
        ...  # build the image, depending of GUI options
        return image_path or image_bytes or image_pillow_object

    @clitogui.shower(on_run=my_running_method)
    def my_cli():
        ...  # regular creation and return of argparse parser

    my_cli(sys.argv).run()

The `my_running_method` is basically called each time user presses `run` button in the GUI generated by clitogui. The returned value would be handled by clitogui, depending of its nature (text, image,…).

**Comment by Nedgang** [comment]
Corrected by PR #6
