### ISSUE TITLE
Circumventing GUI generation without messing with command line arguments

### ISSUE THREAD

**Issue by Aluriak** [Nedgang/clitogui#7]
Currently, the only way to avoid clitogui to generate the gui is to add a `--cli` option to sys.argv. This is ambiguous (it could be an argument used by the user) and not really malleable (you have to modify this before the call to clitogui).

Another way to go would be to inspect arguments passed to `.parse_args()` function. If no arguments are given (`None`), then the GUI should be run. However, if a list of command line arguments are provided, this means the arguments already have been devised. No GUI is needed.

Such a change would enable easy unit testing, without having to bother with sys.argv black magic.

**Comment by Nedgang** [comment]
Close by PR #10
